apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: {{ .Values.coordinator.replicas }}
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: {{ .Values.coordinator.image }}
          ports:
            - containerPort: {{ .Values.coordinator.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
