apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: "worker"  # must match headless service name
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          ports:
            - containerPort: {{ .Values.worker.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata